### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by Timbar09** [oyhpnayiaw-as-micronaut/tvmaze#21]
Our team consists of two members, @Timbar09 and @oyhpnayiaw 

Link to the project [here](https://github.com/orgs/oyhpnayiaw-as-micronaut/projects/2)

**Comment by Nemwel-Boniface** [comment]
## Hello @Timbar09 and @oyhpnayiaw      :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job working on your project so far! :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] KIndly assign the tasks to the responsible persons. eg if a task is supposed to be group task, assign it to both of you and if it is a single person task, let it be assigned to only one person.

**Example showing one where I worked with a partner and assigned group task to both of us**

![image](https://user-images.githubusercontent.com/86318284/216963929-a445fa04-8415-4548-b945-46a929cdcaa2.png)

**This is how your kanban currently looks like un assigned to anyone:**

![image](https://user-images.githubusercontent.com/86318284/216964053-875031d7-45d7-4f25-a55e-080657806107.png)

**How to assign the issues/ tasks**

When you click on a task, on the right side of the page a popup will be shown. Go to assignees and assign each other from there

![image](https://user-images.githubusercontent.com/86318284/216964411-352039f0-d6dd-435a-b09e-883462cd5c07.png)


_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @Nemwel-Boniface @Timbar09 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
